---
- name: Pull and run Docker image
  hosts: linode_server
  become: true

  vars:
    image_name: coffee3333/go_7th_task
    image_tag: tagname
    container_name: http-app_container

  tasks:
    - name: Install python3-docker
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python3-docker

    - name: Pull Docker image
      community.general.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        source: pull

    - name: Run Docker container
      community.general.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "8080:8080"
